Revert "MIPS: IP22, IP28: Define dummy MAX_DMA_CHANNELS to fix build failure"
This reverts commit 12acdd24530b25cdb84632b35e7784487fb4aa0a.

The fix works but causes this build error:

  CC      kernel/dma.o
/home/ralf/src/linux/linux-mips/kernel/dma.c:61:2: error: array index in initializer exceeds array bounds
/home/ralf/src/linux/linux-mips/kernel/dma.c:61:2: error: (near initialization for ‘dma_chan_busy’)
/home/ralf/src/linux/linux-mips/kernel/dma.c:61:2: warning: excess elements in array initializer [enabled by default]
/home/ralf/src/linux/linux-mips/kernel/dma.c:61:2: warning: (near initialization for ‘dma_chan_busy’) [enabled by default]
make[3]: *** [kernel/dma.o] Error 1

on several platforms including fuloong2e, ip22 and ip28: