Fix issues in Android patches when moving to 3.14
1. kuid/kgid compilations errors

2. netfilter compile errors as below
net/netfilter/xt_quota2.c: In function 'q2_get_counter':
net/netfilter/xt_quota2.c:234:2: error: incompatible type for argument 2 of 'proc_set_user'
  proc_set_user(p, quota_list_uid, quota_list_gid);
  ^

3. ipv4 errors as below
net/ipv4/tcp.c: In function 'tcp_sendmsg':
net/ipv4/tcp.c:1292:3: error: incompatible type for argument 1 of 'uid_stat_tcp_snd'
   uid_stat_tcp_snd(current_uid(), copied + copied_syn);